#!/bin/bash

# Define the input and output files
inputFile=$1 
outputFile=$2

# Create or clear the output file
> "$outputFile"

# Add CSV header
echo "Number of Threads,Average Latency,Standard Deviation,Number of Measures" >> "$outputFile"

# Read the input file line by line
while IFS= read -r line
do
    # Check if the line contains "Number of Threads" and extract data
    if [[ "$line" == Number\ of\ Threads:* ]]; then
        threads=$(echo "$line" | cut -d' ' -f4)
    elif [[ "$line" == Average\ Latency:* ]]; then
        latency=$(echo "$line" | cut -d' ' -f3)
    elif [[ "$line" == Standard\ Deviation:* ]]; then
        std_dev=$(echo "$line" | cut -d' ' -f3)
    elif [[ "$line" == Number\ of\ Measures:* ]]; then
        measures=$(echo "$line" | cut -d' ' -f4)
        # Write the extracted data to the CSV file
        echo "$threads,$latency,$std_dev,$measures" >> "$outputFile"
    fi
done < "$inputFile"

echo "CSV file created: $outputFile"
